src/worker.browser/worker.js
src/worker.node/worker.js

Ran into a memory leak that I'm fairly certain is traced back to this. An event emitter handler bound via `.once` only gets removed when that event gets emitted, so the promise never removes both handlers, just whichever handler gets invoked first. Thus, every time .promise gets called, the promise() scope gets leaked.
This PR ensures that whichever state gets called first removes the handler for the other state.
I wasn't sure if I should commit the build artifacts for the PR (couldn't find any contribution guidelines), so I left them out. I can add if they're wanted.

Fix memory leak in worker.promise

---

README.md

I changed just one line in the README to make it clearer how to find the latest version of the script on rawgit.
Version 0.7.2 has a `v` (e.g. `v0.7.2`) in front of the number whereas the previous example (`0.5.3`) didn't.

Newer version apparently have a `v` in front of them

---

bower.json

Change "main" property in bower.json from "dist/thread.brower.js" to correct file name "dist/threads.brower.js"

Fix typo in bower "main" property

---

src/worker.node/slave.js
test/spec/worker.spec.js

Done only for node, because corresponding [browser api](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection) is not yet supported for [workers](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope) by any vendor.
Fixes #49

Handle unhandled promise rejection in Node

---

CHANGELOG.md
src/job.js
test/spec/job.spec.js

The purpose of this PR is to allow progress reports from jobs when they are executed and also when they are submitted to a Pool.

Adding progress

---

README.md

Follow-up PR of #63 by @cajus: Just changing the README, no code changes.
Background: #63 does not build right now. Maybe we can at least merge the documentation fix.

Fix readme: basepath.browser => basepath.web

---

src/config.js
src/index.js
src/pool.js
src/worker.node/worker.js
test/spec/worker.spec.js

The purpose of this PR is to allow the ability to pass spawn parameters to worker processes when utilizing the **thread pool**. 
Use case
```
this._threadPool = new thread.Pool(4)
this._threadPool.run(require.resolve('./BabelWorker'));
this._threadPool.send(input)
```
It appears that there is no convenient way to pass parameters to processes managed by thread pool. 
Therefore, if --max_old_space_size=4096 is set for the parent process then there is no way to adjust this option.

Add option parameter to Pool for passing arguments to worker processes

---

README.md
package.json
src/worker.node/worker.js
test/spec/worker.spec.js

It passes any flag (`execArgv`) from the main process to all threads. When that flag is `--inspect` or `--inspect-brk`, it changes the value of the port so the processes don't try to use the same address. 
This behaviour can be disabled by the user by passing a custom `execArgv`.
Bonus: fixes the build process in local
Fixes #16

Pass process flags to the thread, taking care of inspect ports

---

src/worker.browser/slave.js.txt

Needed to avoid triggering of false CommonJS detection inside some modules (e.g. https://github.com/emn178/js-sha3). When I'm sending to a thread, initialized with `thread.run(someFunction, ['sha3.js'])`, module is expected to behave like plain JS script that just sets some globals. But due to `this.module.exports` initialization performed before calling `importScripts`, it thinks that CommonJS behavior is expected and replaces `this.module.exports` with its own table of methods.
Actually, I'm not sure if this problem should be fixed here or in js-sha3 itself, but checking for `this.module.exports` seems to be pretty reasonable way to detect CommonJS environment, so other projects may be doing it too.

Hiding this.module.exports from importScripts in initByMethod

---

package-lock.json
package.json

See <https://github.com/gulpjs/gulp/issues/2246>. Should make the build in #96 go green again.

Update package `natives` to fix node 11 crash

---

src/defaults.js
src/worker.js

Runtime environment detection may fail and try to use NodeJS workers in a Browser environment. This pull request modifies the detection test to avoids this kind of case.
**Detailed problem and solution**
I am currently migrating a subproject from a project created with vue-cli 2 to a project created to vue-cli 3 (VueJS).
Everything works in the old project.
On the new project, same computer, same browser, [this line fails](https://github.com/andywer/threads.js/blob/master/src/defaults.node.js#L5) due to the lack of `cpu()` method.
After some breakpoints, I discovered a difference between the two versions:
- The old one exposes a `process` without `pid` element, threads.js uses Browser elements and everything works.
- The new one exposes a `process` with a fake `pid` element (always 1). …

Avoid to use node workers in browser

---

README.md
src/master/pool.ts
test/pool.test.ts

See #108. Might or might not close this issue.

Implement pool.completed()

---

src/worker/index.ts

Seems like webpack's `process` polyfill for web builds is not an event emitter. What kind of makes sense on second thought.
Fixes #148.

Only set process listeners if `process.on()` is a function

---

src/observable.ts

Assuming that I have following code:
> worker.ts
```javascript
import { expose } from 'threads/worker';
import FileWriter from './FileWriter';
import { Observable } from 'threads/dist/observable';
let fileWriter = new FileWriter();
const fileWorker = {
writeFile: async ( fileName: string, limit: number ) =>
{
fileWriter.fileName = fileName;
fileWriter.limit = limit;
await fileWriter.writeFile();
fileWriter = new FileWriter();
},
observer:  () =>
{
return Observable.from( fileWriter.subject );
}
};
export type FileWorker = typeof fileWorker;
expose( fileWorker );
```
> FileWriter.ts
```javascript
import * as Fs from 'fs';
import * as Path from 'path';
import { Subject } from 'threads/observable';
export default class FileWriter
{
public readonly subject: Subject<number> = new …
```

Fixed TypeError when observer was not provided into subject

---

src/master/invocation-proxy.ts
src/master/pool-types.ts
src/master/pool.ts
src/observable-promise.ts
test/observable-promise.test.ts

Refactor Pool and ObservablePromise implementation, turn into classes. Gets rid of the huge constructor functions.

Improve code quality

---

docs/usage-pool.md
src/master/pool.ts

Implement `maxQueuedJobs` pool option

---

src/transferable.ts

The `Transfer<T>(payload: T, transferables: Transferable[])` overload did not show up as an IntelliSense tip.

Fix Transfer() signature

---

src/master/implementation.node.ts

We should manually shutdown process if `SIGTERM`/`SIGINT` listeners are installed
nodejs docs (https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_signal_events)
> 'SIGTERM' and 'SIGINT' have default handlers on non-Windows platforms that reset the terminal mode before exiting with code 128 + signal number. **If one of these signals has a listener installed, its default behavior will be removed** (Node.js will no longer exit).
tiny-worker docs (https://github.com/avoidwork/tiny-worker#faq)
> In your core script register a listener for SIGTERM or SIGINT via process.on() which terminates (all) worker process(es) and then gracefully shutdowns via process.exit(0);
**Example:**
Problem: `cluster` workers don't shutdown because `theads.js` has invalid SIGTERM listener.
```js
// …
```

Gracefully shutdown process on SIGTERM

---

src/master/invocation-proxy.ts
src/observable-promise.ts
test/observable-promise.test.ts
test/spawn.test.ts

Replacement of #197.
It's essentially the same commits (thanks, @doochik!), but uses `ObservablePromise.from()` when handling `postMessage()` errors.

Handle postMessage() errors in main thread

---

src/master/spawn.ts

We have some environments (involving Docker containers or Webpack builds, &c., &c.) where (a) setting the timeout via env var is awkward, and (b) some development machines experience timeouts. It would be nice to be able to override the default timeout via parameters.

Allow overriding init timeout via parameters

---

.gitignore
docs/usage-advanced.md
src/common.ts
src/index.ts
src/master/invocation-proxy.ts
src/master/spawn.ts
src/serializers.ts
src/types/messages.ts
src/worker/index.ts
test/lib/serialization.ts
test/serialization.test.ts
test/workers/serialization.ts

Allow registering custom serializers to (de-)serialize class instances and other non-trivial data structures that could normally not be sent using `.postMessage()`.
Anyone got any thoughts on this feature or the API? 😉

Feature: Custom serialization

---

src/master/implementation.node.ts

Hello,
current implementation ignores worker options when ts-node is present. For example is not possible to pass "workerData" to thread.
This PR fixes this case.
Regards
Tomasz

Pass NativeWorker options to ts-node worker implementation

---

src/master/implementation.node.ts

Solving https://github.com/andywer/threads.js/issues/222

Allow threads.js to function even with webpack node externals

---

docs/getting-started.md
src/master/implementation.node.ts

Try the `*.asar.unpack` path if the path contains `.asar/`. See <https://www.electron.build/configuration/configuration#configuration-asarUnpack>.
Fixes andywer/threads-plugin#17.

Make node worker try the `*.asar.unpacked` path

---

src/master/implementation.node.ts

Worker instantiation won't throw immediately, so use ASAR fallback straight away.

Fix ASAR path resolution fix

---

docs/usage.md

Added missing `Thread.terminate` & output to make the example more clear

Update Typescript-Example in Usage-Docs

---

package.json

Add conditional exports to fix cjs consumption for node 14

---

src/master/invocation-proxy.ts
src/types/messages.ts
src/worker/implementation.tiny-worker.ts
src/worker/index.ts

Proxy `.unsubscribe()` calls to worker observables. Fixes #262.

Unsubscribe from worker observables when master unsubscribes

---

src/master/pool.ts

Fixes #270.
When you subscribed to a task's completion too late, it might have been resolved already, but the newly created promise would not know that and stay in a pending state forever.

Subscribe to task completion eagerly

---

docs/usage-pool.md

Document `poolTask.then()` better

---

src/master/implementation.browser.ts
src/types/master.ts

Add CORSWorkaround option + update isAbsoluteURL

---

package.json
src/master/pool.ts
src/types/master.ts
test/transferables.test.ts
test/workers/arraybuffer-xor.ts

Resolve transferable object types on call

---

src/master/implementation.node.ts

by using the built-in conversion from file urls to paths.
Fixes #389

Fix relative paths on Windows

---

src/types/master.ts

In nodejs 10+ worker.terminate returns Promise<number> instead. Kept void return type since thats how tiny worker and browser behaves

Fix type compatibility with node 10+

---

src/master/spawn.ts

In certain situations, `process` may be defined in the browser.
In these cases, it's not sufficient to only check if `process` is defined before trying to access and parse environment variables using `process.env`.

Ensure process and process.env are defined before accessing environment variables

---

worker.mjs

fix: missing isWorkerRuntimer export in esm

---

src/types/master.ts

So the threads.js exported Worker works with bundlers that automatically bundle with import.meta.

Allow url in WorkerImplementation constructor
