- README.md
- src/job.js
- src/pool.js
- test/spec/pool.spec.js
resolve #76 
I will add documents after the code being revewed.
> Add job abortion with tests

- .travis.yml
- karma.conf.js
- package-lock.json
- package.json
Use headless Chrome and Firefox instead. PhantomJS is not just slow, even installing it is a pain...
> Drop phantomjs

- README.md
- src/master/implementation.browser.ts
- src/master/implementation.node.ts
- src/master/implementation.ts
- src/master/index.ts
- src/master/pool.ts
- src/master/spawn.ts
- src/master/thread.ts
- src/observable-promise.ts
- test/pool.test.ts
> Implement thread pool

- .gitignore
- .travis.yml
- README.md
- package-lock.json
- package.json
- src/master/implementation.browser.ts
- src/master/implementation.node.ts
- src/master/implementation.ts
- src/worker/implementation.browser.ts
- src/worker/implementation.tiny-worker.ts
- src/worker/implementation.ts
- src/worker/implementation.worker_threads.ts
- src/worker_threads.ts
- test/webpack/app.ts
- test/webpack/webpack.chromium.mocha.ts
- test/webpack/webpack.node.config.js
- test/webpack/webpack.test.ts
- test/webpack/webpack.web.config.js
- test/webpack/worker.ts
- tsconfig.json
- worker.js
Make library code a bit more bundler-friendly and add tests to make it works with webpack.
> Add webpack support

- README.md
Just a simple documentation update.
> update readme for events to be events()

- src/master/pool.ts
- test/pool.test.ts
Emit event when a task gets cancelled.
> Implement pool event for task cancellation

- README.md
- package.json
Put v1.0 on `master` branch, update readme.
> v1.0 beta launch preparation

- worker.js
> Fix broken `threads/worker` module

- .travis.yml
- README.md
- docs/usage.md
- package.json
- src/master/implementation.node.ts
- test/workers/arraybuffer-xor.ts
- test/workers/count-to-five.ts
- test/workers/counter.ts
- test/workers/faulty-function.ts
- test/workers/hello-world.ts
- test/workers/increment.ts
- test/workers/minmax.ts
- test/workers/top-level-throw.ts
> Auto-enable `ts-node` in `*.ts` workers

- src/master/implementation.node.ts
> Make sure to terminate all workers on master process exit

- src/master/spawn.ts
> Clear timeout when it's no longer needed

- package-lock.json
- package.json
- src/master/implementation.browser.ts
- src/types/master.ts
- test/webpack/app.ts
> Support instantiating workers from absolute URLs

- src/master/get-bundle-url.browser.ts
- src/master/implementation.browser.ts
- src/worker/index.ts
As seen in Solar wallet on Safari.
> Prevent security error when master thread lives on file:// URL

- docs/usage-pool.md
- src/master/pool.ts
- src/ponyfills.ts
- test/pool.test.ts
> Implement and document `pool.settled()`

- src/master/implementation.node.ts
- src/master/spawn.ts
- src/types/master.ts
Pretty much what it says on the box! It would be very handy to be able to control resource limits.
> Allow passing the resourceLimits parameter through to Node's worker_threads

- src/worker/index.ts
> Report original error, too, when reporting double worker error

- package-lock.json
- package.json
- src/worker/implementation.browser.ts
Fixes #242. Fix ported from #228.
> Fix isWorkerRuntime() always returning true in browsers

- docs/usage-observables.md
> Fix observable sample code

- src/master/implementation.browser.ts
- src/master/implementation.node.ts
- src/master/implementation.ts
- src/master/index.ts
- src/worker/index.ts
- test/webpack/addition-worker.ts
- test/webpack/app.ts
Needed to duplicate some logic as importing worker implementations into master thread code didn't seem great.
Closes #225.
> Expose isWorkerRuntime() function

- index.mjs
- observable.mjs
- package.json
- register.mjs
- src/master/implementation.node.ts
- worker.mjs
Finally managed to make `threads` work with node.js ES modules! 🎉
Fixes #220.
> Make library work with node.js ES modules

- src/master/spawn.ts
> Straighten init timeout error message

- src/master/implementation.node.ts
> Fix webpack requires.resolve() expression warnings

- src/master/spawn.ts
- src/types/master.ts
> pass workerData to Node worker_threads

- docs/usage-pool.md
> Document pool task result handling

- package-lock.json
- package.json
- src/observable-promise.ts
See andywer/observable-fns#17.
> Update observable-fns to fix an issue with TypeScript 4.3

- index.mjs
> Export BlobWorker from mjs entrypoint
